# Generated by Django 5.1.4 on 2024-12-30 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typeName', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('percentage', models.FloatField()),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('alcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alcohol.alcohol')),
            ],
        ),
    ]
