# Generated by Django 5.1.4 on 2024-12-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0002_event_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='eventName',
        ),
    ]
