# Generated by Django 5.1.4 on 2024-12-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0003_rename_name_event_eventname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alcohol',
            old_name='typeName',
            new_name='alcoholType',
        ),
    ]
