# Generated by Django 5.1.4 on 2025-01-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0004_rename_typename_alcohol_alcoholtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
