# Generated by Django 5.1.4 on 2025-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0005_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='alcoholType',
            field=models.CharField(choices=[('Wine', 'Wine'), ('Beer', 'Beer'), ('Vodka', 'Vodka'), ('Whiskey', 'Whiskey'), ('Liqueur', 'Liqueur'), ('Cider', 'Cider'), ('Rum', 'Rum'), ('Gin', 'Gin'), ('Brandy', 'Brandy'), ('Tequila', 'Tequila'), ('Cognac', 'Cognac'), ('Other', 'Other')], max_length=100),
        ),
    ]
