# Generated by Django 5.1.4 on 2025-01-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0006_alter_alcohol_alcoholtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Party', 'Party'), ('Meeting with friend', 'Meeting with friend'), ('Work meeting', 'Work meeting'), ('Date', 'Date'), ('Alone', 'Alone'), ('Other', 'Other')], max_length=100),
        ),
    ]
