# Generated by Django 5.1.4 on 2025-01-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0009_rename_chellange_challange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challange',
            old_name='limit',
            new_name='limitAlc',
        ),
    ]
