# Generated by Django 5.1.4 on 2025-01-11 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0010_rename_limit_challange_limitalc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hangoverType', models.CharField(choices=[('restless night', 'restless night'), ('bad mood', 'bad mood'), ('indigestion', 'indigestion')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangovers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
